# .devcontainer/Dockerfile or your project Dockerfile
FROM python:3.12

# system deps for psycopg2
RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
    
WORKDIR /app
COPY . /app
